version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver-link-shorter
    environment:
      CB_ADMIN_NAME: ${DBEAVER_ADMIN_NAME}
      CB_ADMIN_PASSWORD: ${DBEAVER_ADMIN_PASSWORD}
    ports:
      - '5050:8978'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: link-shorter
      JWT_SECRET_KEY: teste
      JWT_EXPIRES_IN: '30 minutes'
      DBEAVER_ADMIN_NAME: cbadmin
      DBEAVER_ADMIN_PASSWORD: 040996Lv
    depends_on:
      - postgres
    ports:
      - '3000:3000'

  elasticsearch:
    image: elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'

  kibana:
    image: kibana:8.16.1
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch

volumes:
  postgres_data:
